### ISSUE TITLE
macOS applications do not run on Mojave

### ISSUE THREAD

**Issue by JoelOtter** [karlsabo/packr#11]
Hey there,

I'm running macOS 10.14.6 (Mojave). The generated .app has a cross through the icon, and trying to run it throws this error:

![image](https://user-images.githubusercontent.com/2765356/85447455-8c795700-b58d-11ea-8982-1e7b9ec6782f.png)

I'm invoking packr (latest) with the following command:

```sh
  java -jar buildTools/packr.jar \
    --platform mac \
    --jdk $JDK_ZIP_MAC_NAME \
    --executable feud \
    --classpath feud_desktop.jar \
    --mainclass com.bearwaves.feud.desktop.AnonymousDesktopLauncher \
    --vmargs Xmx1G \
    --icon desktop/icons.icns \
    --minimizejre ./buildTools/minimise.json \
    --output build/desktop/mac/Feud.app
```

This happens regardless of whether the application is signed.

Is there some configuration option I'm missing? Thanks so much for the fork.

**Comment by karlsabo** [comment]
Thanks, going to try out `-mmacosx-version-min=10.13` as a compile flag and see how that goes.

**Comment by karlsabo** [comment]
I pushed some commits that should build the binary to be compatible with macOS 10.10+. I've attached a packr-all jar for you to try out. Please let me know if it works.

[Packr-2.7.0-SNAPSHOT-all.jar.zip](https://github.com/karlsabo/packr/files/4823052/Packr-2.7.0-SNAPSHOT-all.jar.zip)

**Comment by JoelOtter** [comment]
Thanks so much, that works! I'll close this issue out now. :)
