### ISSUE TITLE
Executable wrapper messes with uncaught exception handler

### ISSUE THREAD

**Issue by Frotty** [karlsabo/packr#14]
I like to use an uncaught exception handler to give the user some feedback upon crashing and also get stacktrace.
This works well when simply running the jar. However when I run the executable, (.exe on windows in my case), the uncaught exception handler is not invoked at all.

I set the exception handler like this: 
```java
Thread.setDefaultUncaughtExceptionHandler((thread, exception) -> {
	log.error(exception.getMessage(), exception);
	exception.printStackTrace();
	try {
		javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
		e.printStackTrace();
	}
	StringWriter sw = new StringWriter();
	exception.printStackTrace(new PrintWriter(sw));
	JTextArea jTextField = new JTextArea();
	jTextField.setText("Please report this crash with the following info:\n" + sw.toString());
	jTextField.setEditable(false);
	JOptionPane.showMessageDialog(null, jTextField, "Uncaught Exception", JOptionPane.ERROR_MESSAGE);
});
```
Then I use a button to throw an uncaught exception as a test:

```java
new Button().addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                throw new RuntimeException("test");
            }
        });
```

Which gives me a dialog like this when running the jar:
![](https://i.imgur.com/KJEee3o.png)

But nothing happens with the .exe (just crash)

**Comment by karlsabo** [comment]
The code is working as expected, see https://github.com/karlsabo/packr/blob/master/PackrAllTestApp/src/main/java/com/nimblygames/packrtestapp/PackrAllTestApplication.java which has an uncaught exception handler.

```java
    Thread.setDefaultUncaughtExceptionHandler((thread, throwable) -> {
            System.out.println("Received uncaught exception");
            throwable.printStackTrace(System.out);
        });

        Thread throwingThread = new Thread(() -> {
            throw new RuntimeException("Unchecked exception from thread " + Thread.currentThread().getName());
        }, "throwing-thread");
        throwingThread.start();
```

I suspect you have a race condition where you're exiting the JVM before the code in setDefaultUncaughtExceptionHandler executes. That code creates the non daemon Swing threads preventing JVM shutdown.

Do you have any logging in com.badlogic.gdx.ApplicationListener#dispose that would indicate the JVM is being shutdown?

**Comment by karlsabo** [comment]
Hmm, interesting. I was thinking about it and your exception should be happening on the main thread, which isn't getting the default exception handler called.

Since I haven't changed how the JVM and main method are executed, I'm not sure how exactly this works. I'll look into it but if you figure it out please make a PR!

**Comment by Frotty** [comment]
> Hmm, interesting. I was thinking about it and your exception should be happening on the main thread, which isn't getting the default exception handler called.
> 
> Since I haven't changed how the JVM and main method are executed, I'm not sure how exactly this works. I'll look into it but if you figure it out please make a PR!

I don't exactly know what you mean - is the exception handler registered for the wrong thread, or the exception thrown in the wrong thread? I could test posting a runnable, but I doubt it makes a difference.
The packr does some "JNI voodoo" from what i heard to run the main class without actually "executing" the jar, which I thought to be the case for this, but dunno.

**Comment by karlsabo** [comment]
Sorry for the confusion. The main method is being called from some C++ code and as you noticed, your default uncaught handler isn't getting called for any exceptions that occur on the main thread. Other threads work, but not the main thread that's getting called from the Packr Launcher.

**Comment by karlsabo** [comment]
I think I found the issue, it looks like Thread#dispatchUncaughtException needs to be called from the C++ code after calling main. I'll try to get a patch out soon.

**Comment by karlsabo** [comment]
Pushed a commit that fixes the issue for me. I'll try to get a patch out this week. Let me know if this works for you.

**Comment by Frotty** [comment]
Thanks a lot for your quick responses @karlsabo 👍 .
Is a snapshot repo available or do I wait for the next release?
Jitpack can't build the native code I believe.

**Comment by karlsabo** [comment]
Yeah, the snapshot is available at https://oss.sonatype.org/content/repositories/snapshots/com/nimblygames/packr

**Comment by karlsabo** [comment]
Yeah, the snapshot is available at https://oss.sonatype.org/content/repositories/snapshots/

I'm on my phone. If I can figure out a direct link to the packr-all file I'll send it. But in Gradle you can use that URL as a repository source.

**Comment by karlsabo** [comment]
Rename the attached zip to a jar and give it a try
[packr-all-2.7.0-SNAPSHOT.zip](https://github.com/karlsabo/packr/files/4842822/packr-all-2.7.0-SNAPSHOT.zip)

**Comment by Frotty** [comment]
@karlsabo Does using `2.7.0-SNAPSHOT` as version in build.gradle achieve the same?
I tried it with that version, and I don't see any change, the dialog still doesn't show.

**Comment by karlsabo** [comment]
Yeah, all you need is the sonatype snapshot repo

```
repositories {
		maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
	}
```

**Comment by karlsabo** [comment]
I've experienced some weirdness with sonatype. Maybe it's giving you an old version. Or Gradle cached an old version. You could try again with `--refresh-dependencies` when executing Gradle.

**Comment by karlsabo** [comment]
Release 2.6.4 is now available on Maven Central.

**Comment by Frotty** [comment]
I finally released a new version with updated .exe, indeed it does work now 👍 
Thanks @karlsabo 🍻
