### ISSUE TITLE
process doesn't close on OSX

### ISSUE THREAD

**Issue by klianc09** [karlsabo/packr#15]
I have the same problem as this issue from the upstream project: https://github.com/libgdx/packr/issues/101 
(I assume it's okay to open a similar issue here, since the issue also seems to be present in this fork)

When closing the window on OSX, the process stays active and it has to be forcefully stopped.

The info on my setup:
- packr-all-2.6.4
- The `macOS x64` JDK8 from https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html
- Tested on an early 2011 MacBook running OSX 10.13.6 High Sierra
- It's a libgdx project  ~and it doesn't matter whether I set `LwjglApplicationConfiguration.forceExit` to true or false~

**Comment by karlsabo** [comment]
Yeah, it's ok to open any issue for something that's not working as expected.

What debugging have you done to try and figure out why the JVM isn't exiting?

Have you run [jstack](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jstack.html) or [visualvm](https://visualvm.github.io/download.html) to inspect which threads are still running?

Have you run the packr launcher with debug on? `-c --verbose --`

Does this only happen when you run your application using packr?

Thanks.

**Comment by klianc09** [comment]
Okay, turns out I messed up when testing `LwjglApplicationConfiguration.forceExit` setting and tested both times with it set to `false`. :disappointed: 

When `LwjglApplicationConfiguration.forceExit` is set to `true` the app packaged with packr quits correctly on MacOS. 
I'm sorry for the false alarm.

**Comment by karlsabo** [comment]
Great, glad you figured it out.
