### ISSUE TITLE
MacOS issues

### ISSUE THREAD

**Issue by Frotty** [karlsabo/packr#9]
Hi, thanks a lot for this fork and the fixes/additions, I found them very useful.

However I can only get the Windows and Linux executables to properly work.

On MacOS when running the executable directly, it seemed to use the system JRE somehow, because even though I package a version 8 JRE, I got the error from https://github.com/libgdx/packr/issues/156 which indicates a 11+ JRE (which is the system one). When running it as an app bundle, after ignoring security warnings, simply nothing happens. On a Mac where the system JRE was 8, it seemed to work.

**Comment by karlsabo** [comment]
Have you tried running with the `--verbose` flag turned on? You should see some debug output that starts with `fileSearch found libjli! filename=`. What does that say? Then there should also be a log statement that starts with `Loading libjli=`. What's the output of that? If you're seeing all that correctly then what does `ls -lah <path to libjli.dylib>` output? Is it a symbolic link?

Does running `gradlew -i PackrLauncher:clean PackrLauncher:build` work for you?

Unless [symbolic] links are involved, I don't see how this is possible.

**Comment by karlsabo** [comment]
Hey @Frotty,

I haven't heard from you and I don't know of any problems, so I'm closing this issue.

**Comment by Frotty** [comment]
Hi, sorry, I forgot to follow up on this.
The problem seemed to have been me using the `cacheJre` option with multiple platforms.
The cache from e.g. win platform jdk had some effect on the mac target, causing .exe and .dll files to be included with the mac package and thus not working.
After removing the cache option, mac and linux builds are now functional. 
Thanks again for the fork ❤️
